### ISSUE TITLE
Unrecognized package dependency type `sdk`

### ISSUE THREAD

**Issue by ScottPierce** [dart-lang/source_gen#126] opened 2017-01-15 06:00 UTC
My pubspec.yaml for my flutter project:
```
dependencies:
  flutter:
    sdk: flutter
  built_collection: ^1.0.0
  built_value: ^0.5.0

dev_dependencies:
  build: ^0.6.0
  build_runner: ^0.1.0
  built_value_generator: ^0.5.0
  source_gen: '>=0.5.0+03 <0.6.0'
  quiver: '>=0.21.0 <0.24.0'
  test: any
```

I was trying to test `built_value` in my flutter project, and I got this error when I ran the generator:
```
pub run ./tool/watch.dart
Unhandled exception:
Unrecognized package dependency type `sdk`
#0      _dependencyType (package:build_runner/src/package_graph/package_graph.dart:171:7)
#1      PackageGraph.PackageGraph.forPath.addNodeAndDeps.<anonymous closure> (package:build_runner/src/package_graph/package_graph.dart:96:41)
#2      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:348)
#3      PackageGraph.PackageGraph.forPath.addNodeAndDeps (package:build_runner/src/package_graph/package_graph.dart:92:12)
#4      PackageGraph.PackageGraph.forPath (package:build_runner/src/package_graph/package_graph.dart:105:23)
#5      PackageGraph.PackageGraph.forThisPackage (package:build_runner/src/package_graph/package_graph.dart:111:48)
#6      BuildOptions.BuildOptions (package:build_runner/src/generate/options.dart:68:26)
#7      build.<build_async_body> (package:build_runner/src/generate/build.dart:54:21)
#8      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

From the error message, it sounds like `source_gen` doesn't like the usage of `sdk` in my pubspec.yaml

**Comment by brianegan** [comment] 2017-01-15 12:05
+1 Ran into this today as well!

**Comment by kevmoo** [comment] 2017-01-15 18:29
We haven't tested this much against flutter projects - should be easy to fix.

**Comment by matanlurey** [comment] 2017-02-17 17:58
FWIW this is a really silly bug - we just need to bump the package resolver to a more recent version that doesn't cry when it sees `sdk: `. I can get out a quick fix, though we'd probably want to add some e2e test for a Flutter application soon.

**Comment by matanlurey** [comment] 2017-02-17 18:00
Waiting for https://github.com/dart-lang/build/issues/211.

**Comment by eseidel** [comment] 2017-03-12 16:55
Still waiting? :)

**Comment by matanlurey** [comment] 2017-03-12 20:59
I need someone to bump `source_gen` and verify, I think.

**Comment by jakemac53** [comment] 2017-03-14 16:33
This shouldn't require a source_gen bump, just a pub upgrade. As soon as somebody verifies we should be able to close this.

**Comment by lkjh654** [comment] 2017-03-17 11:03
I can confirm that the issue is fixed now.

**Comment by matanlurey** [comment] 2017-04-04 04:10
Thanks @lkjh654 👍

**Closed by matanlurey** 2017-04-04 04:10 UTC
